[package]
name = "l-build_apis_with_axum"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version="0.8.4" }
tokio = { version = "1", features = ["full"] }
serde = {version = "1", features = ["derive"] }
serde_json = "1.0"
csv = "1.3.1"
